### ISSUE TITLE
SPARQL over entailed graph

### ISSUE THREAD

**Issue by sven-h** [SemWebNotebooks/Jupyter-RDFify#2]
Hi,

thank you for your library.
We currently use it to enhance our SemWeb exercises with it.
It works out quite well.

One demand which I have for some exercises is to query the entailed graph with SPARQL.
From what I read,  the entailed graph can be only used inside the same cell:

`For now you can only entail graphs in-place`

In the example notebooks it shows that 

```
%rdf graph entail-rdfs -l pets
%rdf graph draw -l pets
```
works, but the SPARQL query would need the cell magic (`%%`)  and not the line magic.

So is it possible to also create queries over entailed graph?

If not, would it be possible to also store the entailed graph in the store with a new label such that we can use this label for SPARQL queries in other cells.
What was the reason behind not storing the entailed graph?

Thank you
Best regards
Sven

**Comment by sven-h** [comment]
Hi,

currently my workaround is
```
from rdflib.plugins.sparql.results.txtresults import TXTResultSerializer
import sys

%rdf graph entail-rdfs+owl -l mygraph
store = %rdf -r
g = store['rdfgraphs']['mygraph']
query = """
SELECT ?result
WHERE {
    ex:Germany rdfs:label ?result
}
"""
TXTResultSerializer(g.query(query)).serialize(sys.stdout, 'UTF-8')
```

(It is important to replace the graph name  -in the example it is `mygraph` )

However, I would be interested to know if there is a better solution.

Best regards
Sven

**Comment by lapie1** [comment]
Sorry for the late answer. With in-place, this definition is meant: https://en.wikipedia.org/wiki/In-place_algorithm
So when entailing a graph, it overwrites the non-entailed graph, this does not mean that you have to query it in the same cell.

This means that you can entail the graph with `%rdf graph entail-rdfs -l pets` in one cell and then query it in the next with `%%rdf sparql -l pets`.

I hope this helps.

Best regards
Lars

**Comment by sven-h** [comment]
Hi Lars,

thank you for your answer.
Want I want to do is to query the **entailed** graph with a SPARQL query.

[Here is a very small example notebook ( I need to zip it because github dosn't support jupyter notebooks directly)](https://github.com/SemWebNotebooks/Jupyter-RDFify/files/7839659/Example.zip) together with my current workaround (which I described above).
Maybe you know if there is a better way instead of writing a code cell with some python code and run the queries inside it.

Thanks

Best regards
Sven

**Comment by lapie1** [comment]
As far as I know, RDFLib does not provide copy functionality for its graphs. And as RDFLib/OWL-RL does only operate in-place on graphs, RDFify does so as well.

It is indeed not possible to entail and query the graph in a single cell (without using python). I have deliberately not added the entailment functionality to the SPARQL submodule, as I think this would result in too much of a side effect as even SELECT queries would make changes to the graph. But it is possible, [as said above](https://github.com/SemWebNotebooks/Jupyter-RDFify/issues/2#issuecomment-1008920979), by first entailing the graph in one cell and then querying the entailed graph in the next one.
[I have changed your notebook to use this approach.](https://github.com/SemWebNotebooks/Jupyter-RDFify/files/7913687/Example.zip)

Best regards
Lars

**Comment by sven-h** [comment]
Hi Lars,

thanks for your reply.
This is exactly what I was searching for.

I thought I also tried this out but maybe not in the exact same way as you did.

Best regards
Sven
